[general]
import = ['~/.config/alacritty/themes/themes/gruvbox_dark.toml']

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
decorations = 'None'
opacity = 0.95
startup_mode = 'Maximized'
option_as_alt = 'Both'

[font]
normal = { family = 'Hack Nerd Font Mono', style = 'Regular' }
size = 14

[selection]
save_to_clipboard = true
