[[mgr.prepend_keymap]]
on = 'T'
run = 'plugin toggle-pane max-current'
desc = 'Show or hide the preview pane'

[[mgr.prepend_keymap]]
on = ['c', 'm']
run = 'plugin chmod'
desc = 'Chmod on selected files'

[[mgr.prepend_keymap]]
on = ['g', 'c']
run = 'plugin vcs-files'
desc = 'Show Git file changes'

[[mgr.prepend_keymap]]
on = ['g', 'C']
run = 'cd ~/.config'
desc = 'Go ~/.config'
