[[manager.prepend_keymap]]
on = 'T'
run = 'plugin toggle-pane max-current'
desc = 'Show or hide the preview pane'

[[manager.prepend_keymap]]
on = ['c', 'm']
run = 'plugin chmod'
desc = 'Chmod on selected files'

[[manager.prepend_keymap]]
on = ['g', 'v']
run = 'plugin vcs-files'
desc = 'Show Git file changes'
