# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 2, 5]
sort_by = "mtime"
sort_reverse = true
sort_dir_first = true
linemode = "permissions"
show_hidden = true
