# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = 'https://yazi-rs.github.io/schemas/yazi.json'

[mgr]
ratio = [1, 2, 3]
mouse_events = []

[plugin]
# prepend_previewers = [{ name = '*.md', run = 'glow' }]

[[plugin.prepend_fetchers]]
id = 'git'
name = '*'
run = 'git'

[[plugin.prepend_fetchers]]
id = 'git'
name = '*/'
run = 'git'

[[plugin.prepend_previewers]]
name = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
