theme = 'gruvbox'

[editor]
line-number = 'relative'
mouse = false
cursorline = true
color-modes = true
idle-timeout = 0
completion-timeout = 5

[editor.statusline]
left = ['mode', 'spinner', 'version-control', 'file-base-name', 'read-only-indicator', 'file-modification-indicator']
center = ['diagnostics']
right = [
    'register',
    'primary-selection-length',
    'selections',
    'file-encoding',
    'file-line-ending',
    'position',
    'position-percentage',
    'total-line-numbers',
]

[editor.lsp]
goto-reference-include-declaration = false

[editor.cursor-shape]
insert = 'underline'

[editor.file-picker]
hidden = false
parents = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[editor.whitespace.render]
tab = 'all'
space = 'none'
nbsp = 'none'
nnbsp = 'none'
newline = 'none'

[editor.indent-guides]
render = true
character = 'â•Ž'
skip-levels = 1
