theme = 'gruvbox'

[editor]
line-number = 'relative'
mouse = false
cursorline = true
color-modes = true
idle-timeout = 0
completion-timeout = 5

[editor.statusline]
left = ['mode', 'spinner', 'version-control', 'file-base-name', 'read-only-indicator', 'file-modification-indicator']
center = ['diagnostics']
right = [
  'register',
  'primary-selection-length',
  'selections',
  'file-type',
  'file-encoding',
  'file-line-ending',
  'position',
  'position-percentage',
  'total-line-numbers',
]

[editor.lsp]
goto-reference-include-declaration = false

[editor.file-picker]
hidden = false
parents = false
ignore = false
git-ignore = false
git-global = false
git-exclude = false

[editor.whitespace.render]
tab = 'all'
space = 'none'
nbsp = 'none'
nnbsp = 'none'
newline = 'none'

[editor.indent-guides]
render = true
character = 'â•Ž'
skip-levels = 1

[keys.normal.space]
v = [':write-all', ':sh zellij run -n Git -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/lazygit.sh']
e = [':sh zellij run -n Yazi -c -f -x 15% -y 15% --width 70% --height 70% -- bash ~/.config/helix/yazi.sh']
q = [':write-all', ':sh zellij run -n Scooter -c -f -x 5% -y 5% --width 90% --height 90% -- bash ~/.config/helix/scooter.sh']
t = [
  'expand_selection',
  ':pipe-to zellij run -n "Go test" -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/gotest.sh $(cat -)',
  'shrink_selection',
]
