[language-server.gopls.config]
gofumpt = true

[language-server.golangci-lint-lsp.config]
command = ['golangci-lint', 'run', '--fast-only', '--output.json.path=stdout', '--show-stats=false', '--issues-exit-code=1']

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
'https://json.schemastore.org/github-workflow.json' = '.github/workflows/*.{yml,yaml}'

[[language-server.typescript-language-server.config.plugins]]
name = '@vue/typescript-plugin'
location = '/opt/homebrew/lib/node_modules/@vue/language-server/'
languages = ['vue']

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[language-server.ruff.config.settings]
lineLength = 140

[[language]]
name = 'yaml'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'yml', '--line-width', '140'] }
auto-format = true

[[language]]
name = 'toml'
formatter = { command = 'taplo', args = ['fmt', '-o', 'column_width=140', '-'] }
auto-format = true

[[language]]
name = 'markdown'
comment-tokens = ['-', '+', '*', '- [ ]', '>']
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'md', '--line-width', '140', '--indent-width', '2'] }
auto-format = true

[[language]]
name = 'sql'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'sql', '--line-width', '140', '--indent-width', '4', '--unstable-sql'] }
auto-format = true

[[language]]
name = 'python'
language-servers = ["ruff", "pyright"]
auto-format = true

[[language]]
name = 'awk'
formatter = { command = 'gawk', timeout = 5, args = ['--file=/dev/stdin', '--pretty-print=/dev/stdout'] }
auto-format = true

[[language]]
name = 'javascript'
language-servers = ['typescript-language-server', 'vscode-eslint-language-server']
auto-format = true

[[language]]
name = 'typescript'
language-servers = ['typescript-language-server', 'vscode-eslint-language-server']
auto-format = true

[[language]]
name = 'vue'
auto-format = true
formatter = { command = 'prettier', args = ['--parser', 'vue'] }
language-servers = ['typescript-language-server']

[[language]]
name = 'lua'
auto-format = true

[[language]]
name = 'bash'
indent = { tab-width = 4, unit = '\t' }
auto-format = true
