[language-server.gopls.config]
gofumpt = true

[language-server.golangci-lint-lsp.config]
command = ['golangci-lint', 'run', '--fast', '--out-format', 'json', '--issues-exit-code=1']

[[language]]
name = 'toml'
indent = { tab-width = 4, unit = '    ' }
formatter = { command = 'taplo', args = ['fmt', '-o', 'indent_string=    ', '-o', 'column_width=140', '-'] }
auto-format = true

[[language]]
name = 'sql'
# formatter = { command = 'sqlformat', args = ['-k', 'upper', '-i', 'lower', '-'] }
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'sql', '--line-width', '140', '--indent-width', '4', '--unstable-sql'] }
auto-format = true

[[language]]
name = 'bash'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'python'
auto-format = true

[[language]]
name = 'json'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'markdown'
indent = { tab-width = 4, unit = '    ' }
comment-tokens = ['-', '+', '*', '- [ ]', '>']
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'md', '--line-width', '140', '--indent-width', '4'] }
auto-format = true

[[language]]
name = 'typescript'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'javascript'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'jsx'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'tsx'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'css'
indent = { tab-width = 4, unit = '    ' }
auto-format = true

[[language]]
name = 'html'
indent = { tab-width = 4, unit = '    ' }
auto-format = true
