[language-server.gopls.config]
gofumpt = true

[language-server.golangci-lint-lsp.config]
command = ['golangci-lint', 'run', '--fast', '--out-format', 'json', '--issues-exit-code=1']

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
'https://json.schemastore.org/github-workflow.json' = '.github/workflows/*.{yml,yaml}'

[language-server.deno-lsp]
command = 'deno'
args = ['lsp']
config.deno.enable = true

[[language]]
name = 'typescript'
roots = ['deno.json', 'deno.jsonc']
auto-format = true
language-servers = ['deno-lsp']

[[language]]
name = 'javascript'
roots = ['deno.json', 'deno.jsonc']
auto-format = true
language-servers = ['deno-lsp']

[[language]]
name = 'yaml'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'yml', '--line-width', '140'] }
auto-format = true

[[language]]
name = 'lua'
auto-format = true

[[language]]
name = 'toml'
formatter = { command = 'taplo', args = ['fmt', '-o', 'column_width=140', '-'] }
auto-format = true

[[language]]
name = 'sql'
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'sql', '--line-width', '140', '--indent-width', '4', '--unstable-sql'] }
auto-format = true

[[language]]
name = 'python'
auto-format = true

[[language]]
name = 'markdown'
comment-tokens = ['-', '+', '*', '- [ ]', '>']
formatter = { command = 'deno', args = ['fmt', '-', '--ext', 'md', '--line-width', '140', '--indent-width', '2'] }
auto-format = true

[[language]]
name = 'awk'
formatter = { command = 'gawk', timeout = 5, args = ['--file=/dev/stdin', '--pretty-print=/dev/stdout'] }
auto-format = true
