gui:
  scrollHeight: 3
  mouseEvents: false
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  showNumstatInFilesView: true
  showCommandLog: false
  nerdFontsVersion: "3"
  showBranchCommitHash: true
  filterMode: fuzzy

  authorColors:
    "凌凌漆": red

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  parseEmoji: true

os:
  edit: 'zellij action toggle-floating-panes; zelli action write 27; zellij action write-chars ":open {{filename}}"; zellij action write 13'
  editAtLine: 'zellij action toggle-floating-panes; zelli action write 27; zellij action write-chars ":open {{filename}}:{{line}}"; zellij action write 13'
  editAtLineAndWait: 'zellij action toggle-floating-panes; zelli action write 27; zellij action write-chars ":open {{filename}}:{{line}}"; zellij action write 13'
  editInTerminal: true
  openDirInEditor: 'zellij action toggle-floating-panes; zelli action write 27; zellij action write-chars ":open {{dir}}"; zellij action write 13'

promptToReturnFromSubprocess: false
disableStartupPopups: true
