gui:
  scrollHeight: 3
  mouseEvents: false
  sidePanelWidth: 0.25
  expandFocusedSidePanel: true
  showNumstatInFilesView: true
  showCommandLog: false
  nerdFontsVersion: "3"
  showBranchCommitHash: true
  filterMode: fuzzy

  authorColors:
    "凌凌漆": red

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  parseEmoji: true

promptToReturnFromSubprocess: false
disableStartupPopups: true
