large_body_size: 1000000
preview_templates: true
input_bindings:
  up: [k]
  down: [j]
  left: [h]
  right: [l]
  scroll_left: [shift h]
  scroll_right: [shift l]
  previous_pane: [shift k]
  next_pane: [shift j]
  page_up: [ctrl b]
  page_down: [ctrl f]
  select_recipe_list: [w]
  select_response: [s]
  reload_collection: [r]
  history: [ctrl h]
  reset: [z]
  edit: [e]
theme:
  primary_color: Blue
  primary_text_color: White
  secondary_color: Yellow
  success_color: Green
  error_color: Red
